### ISSUE TITLE
[website] unable to build; "RangeError: Invalid time value"

### ISSUE THREAD

**Issue by noureddin** [pbek/QOwnNotes#2394]
I've been trying to build the website locally (as part of #2382). I've followed the instructions at <https://github.com/pbek/QOwnNotes/tree/develop/webpage#readme>, but I still get this stream of errors when I run `yarn run dev` after successful `yarn install` in `webpage/` after a clean clone of the repo. I've tried several times, I literally deleted the local repo and cloned it again, and deleted my `/usr/lib/node_modules` before a `yarn install`. I wasn't able to find relevant information online.

<details><summary>Expand the stdout+stderr of <code>yarn run dev</code></summary>

```
yarn run v1.22.17
$ vuepress dev src
wait Extracting site metadata...
tip Apply local theme at /home/nour/src/QOwnNotes/webpage/src/.vuepress/theme...
tip Apply theme local (extends @vuepress/theme-default) ...
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/nprogress (i.e. "@vuepress/plugin-nprogress") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin @vuepress/last-updated (i.e. "@vuepress/plugin-last-updated") ...
tip Apply plugin mermaidjs (i.e. "vuepress-plugin-mermaidjs") ...
tip Apply plugin code-copy (i.e. "vuepress-plugin-code-copy") ...
tip Apply plugin seo (i.e. "vuepress-plugin-seo") ...
tip Apply plugin sitemap (i.e. "vuepress-plugin-sitemap") ...
tip Apply plugin matomo (i.e. "vuepress-plugin-matomo") ...
tip Apply plugin feed (i.e. "vuepress-plugin-feed") ...
tip Apply plugin canonical (i.e. "vuepress-plugin-canonical") ...
RangeError: Invalid time value
    at Date.toISOString (<anonymous>)
    at Object.modifiedAt (/home/nour/src/QOwnNotes/webpage/node_modules/vuepress-plugin-seo/index.js:64:77)
    at extendPageData (/home/nour/src/QOwnNotes/webpage/node_modules/vuepress-plugin-seo/index.js:27:37)
    at /home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/Page.js:293:19
    at Array.map (<anonymous>)
    at Page.enhance (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/Page.js:290:17)
    at Page.process (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/Page.js:148:16)
    at async App.addPage (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:354:5)
    at async /home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:339:7
    at async Promise.all (index 75)
    at async App.resolvePages (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:337:5)
    at async App.process (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:115:5)
    at async dev (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/index.js:17:3)
Error: [vuepress-plugin-seo] execute extendPageData failed.
    at /home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/Page.js:296:19
    at Array.map (<anonymous>)
    at Page.enhance (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/Page.js:290:17)
    at Page.process (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/Page.js:148:16)
    at async App.addPage (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:354:5)
    at async /home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:339:7
    at async Promise.all (index 75)
    at async App.resolvePages (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:337:5)
    at async App.process (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/node/App.js:115:5)
    at async dev (/home/nour/src/QOwnNotes/webpage/node_modules/@vuepress/core/lib/index.js:17:3)
[...]
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
</details>

Where the `[...]` stands for the block from `RangeError: Invalid time value` to `at async Promise.all`, repeated literally 288 more times, identically, with only the `index` changing (and increasing, until it reaches `index 451`).

If it's relevant, I've successfully built VuePress "helloworld" project, `create-vuepress-site`.

**Comment by pbek** [comment]
Where did you build it on? I only tested Linux so far...

I never saw this error.
Maybe you were hit by https://github.com/ekoeryanto/vuepress-plugin-sitemap/issues/16?

**Comment by noureddin** [comment]
I'm on Linux, too. Specifically, (K)Ubuntu 20.04, with yarn 1.22.17 and nodejs v16.13.2.

Yes, commenting out last-updated line in `config.js` removes the error and builds the website!
But I couldn't use the purposed fix; I still have the same error when I do.

I can only build the website if I disable the last-updated plugin, which is not an issue to me.

Thank you! :smile:

**Comment by pbek** [comment]
> I can only build the website if I disable the last-updated plugin, which is not an issue to me.

Yes, you don't need that! Great!
