### ISSUE TITLE
[BUG] AppImage Qt6 on clean Ubuntu 24.04 prints warning "Incompatible version of OpenSSL"

### ISSUE THREAD

**Issue by o-l-a-v** [pbek/QOwnNotes#3174]
#### Expected behaviour

Clean install of Ubuntu 24.04 x64 with `libfuse2` just installed.

```bash
ubnt@ubnt:~/Desktop$ QT_DEBUG_PLUGINS=1 ./QOwnNotes-x86_64-Qt6.AppImage
Warning: Could not find the Qt platform plugin "wayland" in "" (:0, )
Warning: Incompatible version of OpenSSL (built with OpenSSL >= 3.x, runtime version is < 3.x) (:0, )
Warning: The backend "cert-only" does not support QSslKey (:0, )
Warning: Active TLS backend does not support key creation (:0, )
Warning: The backend "cert-only" does not support QSslKey (:0, )
Warning: Active TLS backend does not support key creation (:0, )
Warning: The backend "cert-only" does not support QSslKey (:0, )
Warning: Active TLS backend does not support key creation (:0, )
Warning: The backend "cert-only" does not support QSslKey (:0, )
Warning: Active TLS backend does not support key creation (:0, )
Warning: The backend "cert-only" does not support QSslKey (:0, )
Warning: Active TLS backend does not support key creation (:0, )
Warning: The backend "cert-only" does not support QSslKey (:0, )
Warning: Active TLS backend does not support key creation (:0, )
Warning: The backend "cert-only" does not support QSslSocket (:0, )
Warning: The backend named "cert-only" does not support TLS (:0, )
Warning: QSslSocket::connectToHostEncrypted: TLS initialization failed (:0, )
Warning: QSslSocket::connectToHostEncrypted: TLS initialization failed (:0, )
Warning: QSslSocket::connectToHostEncrypted: TLS initialization failed (:0, )
Warning: "Removed database file: " "/home/ubnt/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite" (:0, )
Segmentation fault (core dumped)
ubnt@ubnt:~/Desktop$
```

Seems it fails to create a TLS connection due to incompatible version of OpenSSL?

#### Actual behaviour

Should successfully create TLS connection.

#### Steps to reproduce

1. Clean install of Ubuntu 24.04 x64
2. `sudo apt install fuse2`
3. `chmod a+x QOwnNotes-x86_64-Qt6.AppImage`
4. `QT_DEBUG_PLUGINS=1 ./QOwnNotes-x86_64-Qt6.AppImage`

#### Output from the debug section in the settings dialog

<details><summary>Expand</summary>

```markdown
QOwnNotes Debug Information
===========================

## General Info

**Current Date**: `Sun Dec 8 13:53:29 2024`
**Version**: `24.12.1`
**Build date**: `Dec  5 2024`
**Build number**: `1143`
**Platform**: `linux (xcb)`
**Operating System**: `Ubuntu 24.04.1 LTS`
**Build architecture**: `x86_64`
**Current architecture**: `x86_64`
**Release**: `AppImage`
**Qt Version (build)**: `6.5.3`
**Qt Version (runtime)**: `6.5.3`
**Portable mode**: `no`
**Settings path / key**: `/home/ubnt/.config/PBE/QOwnNotes.conf`
**Application database path**: `/home/ubnt/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite`
**Application arguments**: `/tmp/.mount_QOwnNoobXse3/AppRun.wrapped`
**Qt Debug**: `0`
**Locale (system)**: `en_US`
**Locale (interface)**: *empty*
**Primary screen resolution**: `2310x1199`
**Icon theme**: `Adwaita`
**Notes in current note folder**: `2`
**Calendar items**: `0`
**Enabled scripts**: `0`
**Database drivers**: `QSQLITE, QMARIADB, QMYSQL, QODBC, QPSQL`

## Server Info

**serverUrl**: *empty*
**appIsValid**: `no`
**notesPathExists**: *empty*
**connectionErrorMessage**: *empty*

## Spellchecking

**Enabled**: `true`
**Selected language**: `en_US`
**Language codes**: `en_US`
**Language names**: `American English (United States)`
**Application dictionaries path**: `/home/ubnt/.local/share/PBE/QOwnNotes/dicts`

## Note folders

**currentNoteFolderId**: `1`

### Note folder `default`

**id**: `1`
**isCurrent**: `yes`
**activeTagId**: `0`
**localPath**: `/home/ubnt/Notes`
**remotePath**: `Notes`
**cloudConnectionId**: `1`
**isShowSubfolders**: `no`
**isUseGit**: `no`
**allowDifferentNoteFileName**: `no`
**activeNoteSubFolder name**: *empty*
**database file**: `/home/ubnt/Notes/notes.sqlite`

## Cloud connections

### Cloud connection `Default`

**id**: `1`
**isCurrent**: `yes`
**serverUrl**: *empty*
**username**: *empty*
**accountId**: *empty*

## Enabled scripts

## Settings

**Editor/CurrentSchemaKey** (QString): `EditorColorSchema-6033d61b-cb96-46d5-a3a8-20d5172017eb`
**Editor/removeTrailingSpaces** (bool): `false`
**LastUpdateCheck** (QDateTime): `2024-12-08T13:53:15.570`
**MainWindow/mainToolBar.iconSize** (int): `24`
**MainWindow/noteTextEdit.code.font** (QString): `monospace,9,-1,2,400,0,0,0,0,0,0,0,0,0,0,1`
**MainWindow/noteTextEdit.font** (QString): `Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1`
**MainWindow/noteTextView.code.font** (QString): `monospace,9,-1,2,400,0,0,0,0,0,0,0,0,0,0,1`
**MainWindow/noteTextView.font** (QString): `Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1`
**PiwikClientId** (QString): `<hidden>`
**SettingsDialog/geometry** (QByteArray): `<binary data>`
**WelcomeDialog/geometry** (QByteArray): `<binary data>`
**allowNoteEditing** (bool): `true`
**allowOnlyOneAppInstance** (bool): `true`
**appMetrics/notificationShown** (bool): `true`
**checkSpelling** (bool): `true`
**cryptoKey** (qlonglong): `<hidden>`
**currentNoteFolderId** (int): `1`
**currentWorkspace** (QString): `initial`
**darkMode** (bool): `false`
**demoNotesCreated** (bool): `true`
**disableAutomaticUpdateDialog** (bool): `false`
**dockWasInitializedOnce** (bool): `true`
**guiFirstRunInit** (bool): `true`
**initialLayoutIdentifier** (QString): `minimal`
**itemHeight** (int): `17`
**markdownHighlightingEnabled** (bool): `true`
**noteEditIsCentralWidget** (QString): `true`
**noteFileExtensionList** (QStringList): `md, txt`
**notesPath** (QString): `/home/ubnt/Notes`
**ownCloud/supportEnabled** (bool): `false`
**ownCloudInfo/appIsValid** (bool): `false`
**ownCloudInfo/connectionErrorMessage** (QString): *empty*
**ownCloudInfo/notesPathExistsText** (QString): *empty*
**ownCloudInfo/serverVersion** (QString): *empty*
**showMenuBar** (bool): `true`
**showStatusBar** (bool): `true`
**spellCheckLanguage** (QString): `en_US`
**webAppClientService/token** (QString): `<hidden>`
**workspace-initial/name** (QString): `Minimal`
**workspace-initial/noteSubFolderDockWidgetVisible** (QString): `true`
**workspace-initial/windowState** (QByteArray): `<binary data>`
**workspaces** (QStringList): `initial`

## System environment

**APPDIR**: `/tmp/.mount_QOwnNoobXse3`
**APPIMAGE**: `/home/ubnt/Desktop/QOwnNotes-x86_64-Qt6.AppImage`
**ARGV0**: `./QOwnNotes-x86_64-Qt6.AppImage`
**COLORTERM**: `truecolor`
**DBUS_SESSION_BUS_ADDRESS**: `unix:path=/run/user/1000/bus`
**DEBUGINFOD_URLS**: `https://debuginfod.ubuntu.com `
**DESKTOP_SESSION**: `ubuntu`
**DISPLAY**: `:0`
**GDMSESSION**: `ubuntu`
**GNOME_DESKTOP_SESSION_ID**: `this-is-deprecated`
**GNOME_SETUP_DISPLAY**: `:1`
**GNOME_SHELL_SESSION_MODE**: `ubuntu`
**GNOME_TERMINAL_SCREEN**: `/org/gnome/Terminal/screen/8a3af883_15de_4d4d_9827_b71b563caa93`
**GNOME_TERMINAL_SERVICE**: `:1.111`
**GSM_SKIP_SSH_AGENT_WORKAROUND**: `true`
**GTK_MODULES**: `gail:atk-bridge`
**HOME**: `/home/ubnt`
**IM_CONFIG_PHASE**: `1`
**LANG**: `en_US.UTF-8`
**LESSCLOSE**: `/usr/bin/lesspipe %s %s`
**LESSOPEN**: `| /usr/bin/lesspipe %s`
**LOGNAME**: `ubnt`
**LS_COLORS**: `rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:*~=00;90:*#=00;90:*.bak=00;90:*.crdownload=00;90:*.dpkg-dist=00;90:*.dpkg-new=00;90:*.dpkg-old=00;90:*.dpkg-tmp=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:*.swp=00;90:*.tmp=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:`
**MEMORY_PRESSURE_WATCH**: `/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/session.slice/org.gnome.Shell@wayland.service/memory.pressure`
**MEMORY_PRESSURE_WRITE**: `c29tZSAyMDAwMDAgMjAwMDAwMAA=`
**OWD**: `/home/ubnt/Desktop`
**PATH**: `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin`
**PWD**: `/home/ubnt/Desktop`
**QT_ACCESSIBILITY**: `1`
**QT_DEBUG_PLUGINS**: `1`
**QT_IM_MODULE**: `ibus`
**QT_QPA_PLATFORMTHEME**: `gtk2`
**SESSION_MANAGER**: `local/ubnt:@/tmp/.ICE-unix/2384,unix/ubnt:/tmp/.ICE-unix/2384`
**SHELL**: `/bin/bash`
**SHLVL**: `1`
**SSH_AUTH_SOCK**: `/run/user/1000/keyring/ssh`
**SYSTEMD_EXEC_PID**: `2436`
**TERM**: `xterm-256color`
**USER**: `ubnt`
**USERNAME**: `ubnt`
**VTE_VERSION**: `7600`
**WAYLAND_DISPLAY**: `wayland-0`
**XAUTHORITY**: `/run/user/1000/.mutter-Xwaylandauth.IL9OY2`
**XDG_CONFIG_DIRS**: `/etc/xdg/xdg-ubuntu:/etc/xdg`
**XDG_CURRENT_DESKTOP**: `ubuntu:GNOME`
**XDG_DATA_DIRS**: `/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop`
**XDG_MENU_PREFIX**: `gnome-`
**XDG_RUNTIME_DIR**: `/run/user/1000`
**XDG_SESSION_CLASS**: `user`
**XDG_SESSION_DESKTOP**: `ubuntu`
**XDG_SESSION_TYPE**: `wayland`
**XMODIFIERS**: `@im=ibus`
```

</details>

#### Relevant log output in the Log panel

<details><summary>Expand</summary>

```log
[13:54:54] [debug] updatePanelMenu - 'updatePanelMenu'
[13:54:54] [debug] checking directory path "/tmp/.mount_QOwnNor9c6PD/usr/plugins/accessiblebridge" ...
[13:54:54] [debug] checking directory path "/tmp/.mount_QOwnNor9c6PD/usr/bin/accessiblebridge" ...
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [warning] The backend "cert-only" does not support QSslKey
[13:54:54] [warning] Active TLS backend does not support key creation
[13:54:54] [warning] The backend "cert-only" does not support QSslKey
[13:54:54] [warning] Active TLS backend does not support key creation
[13:54:54] [warning] The backend "cert-only" does not support QSslSocket
[13:54:54] [warning] The backend named "cert-only" does not support TLS
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [warning] onResult - 'network reply error': QNetworkReply::UnknownNetworkError
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
[13:54:54] [info] "QOwnNotes server listening on port 22222"
[13:54:54] [debug] on_noteTreeWidget_itemSelectionChanged
[13:54:54] [debug] setCurrentNote - 'note': Note: <id>1 <name>"Markdown Cheatsheet" <fileName>"Markdown Cheatsheet.md" <noteSubFolderId>0 <relativePath>"" <hasDirtyData>false - 'updateNoteText': true - 'updateSelectedNote': false
[13:54:54] [debug] currentLocalPath - 'currentLocalPath': "/home/ubnt/Notes"
[13:54:54] [debug] added to history: NoteHistoryItem: <noteName>"Markdown Cheatsheet" <noteSubFolderPathData>"" <cursorPosition>0 <relativeScrollBarPosition>0
[13:54:54] [warning] QSslSocket::connectToHostEncrypted: TLS initialization failed
```

</details>

**Comment by pbek** [comment]
And what is the warning `Warning: "Removed database file: " "/home/ubnt/.local/share/PBE/QOwnNotes/QOwnNotes.sqlite" (:0, )` 🤔 Never saw that before somewhere...

**Comment by pbek** [comment]
The AppImage currently needs to build [built on Ubuntu 20.04](https://github.com/pbek/QOwnNotes/blob/67958ef372fa64fc57adbd90f558567a3731f8cb/.github/workflows/build-release.yml#L173), but on theory it should work on all library versions after that.
Seems like this is only works in theory after all...

**Comment by o-l-a-v** [comment]
Is OpenSSL included in the app image like discussed in this issue?

* <https://github.com/AppImage/AppImageKit/issues/998>
  * <https://github.com/AppImage/AppImageKit/issues/998#issuecomment-543368166>

Isn't the whole point of an AppImage to have "batteries included", only libfuse2 required on the host?

**Comment by pbek** [comment]
I just downloaded the latest Ubuntu 24.04 image, installed it in a VM, installed libfuse2, downloaded https://github.com/pbek/QOwnNotes/releases/download/v24.12.1/QOwnNotes-x86_64.AppImage and ran it flawlessly.

And now I see what I didn't read... You are using the `QOwnNotes-x86_64-Qt6.AppImage`. Yes, that's not working at all yet.

If you want to work on the build process in the GitHub workflow, you can do so in: https://github.com/pbek/QOwnNotes/blob/221960166d4b5bec81df26334f3e1c2dddca29e2/.github/workflows/build-release.yml#L168-L230

Would be very much apprechated!

**Comment by pbek** [comment]
Maybe also see #3074.

**Comment by pbek** [comment]
## 26.3.14

- Fixed the AppImage deployment in the GitHub release workflows so the bundled
  OpenSSL libraries work again and the script repository loads correctly
  (for [#3502](https://github.com/pbek/QOwnNotes/issues/3502))
  - The SSL issues with the Qt6 AppImage should also be fixed
    (for [#3174](https://github.com/pbek/QOwnNotes/issues/3174))

**Comment by pbek** [comment]
There now is a new release, could you please test it and report if it works for you?

**Comment by pbek** [comment]
Currently, best test https://github.com/pbek/QOwnNotes/actions/runs/23266457006/artifacts/5994686832 of https://github.com/pbek/QOwnNotes/actions/runs/23266457006. It should also have the scripting engine fixed!

**Comment by o-l-a-v** [comment]
@pbek 

I tested the Qt6 AppImage from the GitHub actions artifact on Pop!_OS 22.04.

No errors about OpenSSL anymore, but it suddenly crashes with last message in the terminal "Segmentation fault (core cumped)".

```bash
pop@pop-os:~/Desktop$ chmod +x QOwnNotes-x86_64-Qt6.AppImage
pop@pop-os:~/Desktop$ QT_DEBUG_PLUGINS=1 ./QOwnNotes-x86_64-Qt6.AppImage
Warning: Unable to find dictionary for "C" in path "/C" (:0, )
Warning: QMetaObject::connectSlotsByName: No matching signal for on_actionCopy_note_filename_to_clipboard_triggered() (:0, )
Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
Warning: QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0 ((null):0, (null))
Segmentation fault (core dumped)
pop@pop-os:~/Desktop$
```

**Comment by pbek** [comment]
Which version did you test? 🤔

**Comment by o-l-a-v** [comment]
> Currently, best test https://github.com/pbek/QOwnNotes/actions/runs/23266457006/artifacts/5994686832 of https://github.com/pbek/QOwnNotes/actions/runs/23266457006. It should also have the scripting engine fixed!

This one.

Edit: Or maybe not, will try that one too just in case.

**Comment by o-l-a-v** [comment]
Yes, that one. Or at least it happens with that too. Window opens briefly, then crashes.

**Comment by o-l-a-v** [comment]
I tried running it with `gdb`.

```bash
Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
0x00007ffff7864260 in QAbstractScrollArea::viewport() const () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Widgets.so.6
(gdb) bt
#0  0x00007ffff7864260 in QAbstractScrollArea::viewport() const () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Widgets.so.6
#1  0x0000555555877404 in ?? ()
#2  0x00007ffff553d45a in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#3  0x00007ffff777efb1 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Widgets.so.6
#4  0x00007ffff553d6ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#5  0x00007ffff77c61eb in QWidgetPrivate::setWindowIcon_helper() () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Widgets.so.6
#6  0x00007ffff77c7fdd in QWidget::setWindowIcon(QIcon const&) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Widgets.so.6
#7  0x000055555587d76b in ?? ()
#8  0x000055555587c2b7 in ?? ()
#9  0x000055555592f703 in ?? ()
#10 0x00007ffff559ba50 in ?? () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#11 0x00007ffff5cbad52 in QNetworkAccessManager::finished(QNetworkReply*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Network.so.6
#12 0x00007ffff5cbbb02 in ?? () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Network.so.6
#13 0x00007ffff559b6e2 in ?? () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#14 0x00007ffff5d56de1 in ?? () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Network.so.6
#15 0x00007ffff558cd8c in QObject::event(QEvent*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#16 0x00007ffff777efc2 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Widgets.so.6
#17 0x00007ffff553d6ba in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#18 0x00007ffff55408bd in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#19 0x00007ffff57e7e83 in ?? () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#20 0x00007ffff4f0cd3b in g_main_context_dispatch () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libglib-2.0.so.0
#21 0x00007ffff4f62488 in ?? () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libglib-2.0.so.0
#22 0x00007ffff4f0a3e3 in g_main_context_iteration () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libglib-2.0.so.0
#23 0x00007ffff57e780a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#24 0x00007ffff5548f6b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#25 0x00007ffff55457ce in QCoreApplication::exec() () from /tmp/.mount_QOwnNoZ5xNZM/usr/bin/../lib/libQt6Core.so.6
#26 0x000055555568a400 in ?? ()
#27 0x00007ffff4c29d90 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#28 0x00007ffff4c29e40 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#29 0x000055555568c0b5 in ?? ()
```

**Comment by o-l-a-v** [comment]
Now I tried `https://github.com/pbek/QOwnNotes/releases/download/v26.3.17/QOwnNotes-x86_64-Qt6-experimental.AppImage` from release 26.3.17, it does not crash. 🤔

```bash
pop@pop-os:~/Desktop$ QT_DEBUG_PLUGINS=1 ./QOwnNotes-x86_64-Qt6-experimental.AppImage
Warning: Unable to find dictionary for "C" in path "/C" (:0, )
Warning: QMetaObject::connectSlotsByName: No matching signal for on_actionCopy_note_filename_to_clipboard_triggered() (:0, )
Info: "QOwnNotes server listening on port 22222" ((null):0, (null))
Warning: QFont::setPointSizeF: Point size <= 0 (0.000000), must be greater than 0 ((null):0, (null))
QMetaObject::invokeMethod: No such method QWidget::log(LogWidget::LogType,QString)
QMetaObject::invokeMethod: No such method QWidget::log(LogWidget::LogType,QString)
Segmentation fault (core dumped)
pop@pop-os:~/Desktop$
```

**Comment by pbek** [comment]
> Now I tried https://github.com/pbek/QOwnNotes/releases/download/v26.3.17/QOwnNotes-x86_64-Qt6-experimental.AppImage from release 26.3.17, it does not crash.

It does or it does not? (Since you posted a Segmentation fault)

**Comment by o-l-a-v** [comment]
It worked. The segfault message was there after I closed the window.

**Comment by pbek** [comment]
So it seg-faulted when you quit the app?

**Comment by o-l-a-v** [comment]
Looks like it did. Tried with gdb too, it did not find any issues. I can try it again later today or tomorrow.

**Comment by pbek** [comment]
Yes please, I think I did not have an issue.

**Comment by pbek** [comment]
Can't reproduce this issue, https://github.com/pbek/QOwnNotes/issues/3511#issuecomment-4104497739 can't either... 🤔
